Traceback (most recent call last):
  File "/Users/gracehuckins/miniconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/gracehuckins/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gracehuckins/miniconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gracehuckins/miniconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/gracehuckins/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/gracehuckins/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/gracehuckins/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([4,5,6,7])
print(x+y)
print(x+z)
------------------

----- stdout -----
[5 7 9]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 5[0m
[1;32m      3[0m z [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m4[39m,[38;5;241m5[39m,[38;5;241m6[39m,[38;5;241m7[39m])
[1;32m      4[0m [38;5;28mprint[39m(x[38;5;241m+[39my)
[0;32m----> 5[0m [38;5;28mprint[39m(x[38;5;241m+[39mz)

[0;31mValueError[0m: operands could not be broadcast together with shapes (3,) (4,) 

